Q1. Difference in data type between variables list_ and array_list

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'str'>
Data type of array_list: <U1


Explanation:

list_ contains string elements (like '1', '2', etc.).
array_list is created using np.array() which converts the elements to a common data type (<U1 which means Unicode string of length 1) unless specified otherwise.

Q2. Print data type of each element in list_ and array_list

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements
print("Data type of each element in list_:")
for elem in list_:
    print(type(elem))

print("\nData type of each element in array_list:")
for elem in array_list:
    print(type(elem))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Explanation:

type(elem) within the loop will print the data type of each element in list_ and array_list.

Q3. Difference in data type after explicitly converting array_list elements to int

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements
print("Data type of each element in list_:")
for elem in list_:
    print(type(elem))

print("\nData type of each element in array_list:")
for elem in array_list:
    print(type(elem))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Explanation:

After specifying dtype=int, array_list will contain elements of integer type (int64 by default in this case).

Q4. Characteristics of num_array

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Shape and size of num_array
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Explanation:

.shape gives the dimensions (shape) of the array (2, 3) in this case.
.size gives the total number of elements in the array 6 in this case.

Q5. Create a numpy array of zeros with shape (3, 3)

In [6]:
import numpy as np

zeros_array = np.zeros((3, 3))
print("3x3 Matrix of Zeros:")
print(zeros_array)


3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Explanation:

np.zeros((3, 3)) creates a 3x3 matrix filled with zeros.

Q6. Create an identity matrix of shape (5, 5)

In [8]:
import numpy as np

identity_matrix = np.eye(5)
print("Identity Matrix of shape (5, 5):")
print(identity_matrix)


Identity Matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Explanation:

np.eye(5) creates a 5x5 identity matrix, where all diagonal elements are 1 and all off-diagonal elements are 0.
These examples demonstrate basic operations with NumPy arrays, including data type handling, array creation, and matrix operations. Adjust parameters such as shape and data types as needed for your specific requirements.